image: ruby2.0.0
env:
  - SECRET_KEY_BASE:                  SECRET_KEY_BASE
  - GITHUB_CLIENT_ID:                 GITHUB_CLIENT_ID
  - GITHUB_CLIENT_SECRET:             GITHUB_CLIENT_SECRET
  - HEAD_ENCRYPTION_SECRET_KEY:       HEAD_ENCRYPTION_SECRET_KEY
  - BASE_URL:                         http://localhost:3000
  - RAILS_BEST_PRACTICE_URL:          http://localhost:3001
  - RAILS_SECURITY_URL:               http://localhost:3002
  - REDISTOGO_URL:                    redis://127.0.0.1:6379
  - GOOGLE_ANALYTICS_WEB_PROPERTY_ID: UA-48995135-1
script:
  - bundle install
  - bundle exec rake db:setup
  - bundle exec rspec
services:
  - redis
notify:
  email:
    recipients:
      - koichiro@sideci.com
